plan error::catch_plan {
 return run_plan('error::err', '_catch_errors' => true)
}
